# NumPy Notebook


### Numpy and Numpy Array
Def: NumPy is the package for scientific computing in Python that does array-based calculations and linear algebra.

A NumPy array is an array of data that are all the same type of data that can also be any number of dimensional (N-dimensional).

In [11]:
#import numpy as np as a shorthand
import numpy as np

#python array 
array_python = [2,4,6,8]

#array1 array is a one dimensional 
array1 = np.array([3, 333, 3333.])

#array2 is a two dimensional array with the data type 
array2 = np.array([[2., 4., 6.],[123., 321., 213.]])

## Data Type
Array1 has multiple data types but an array must have the same data type so it is ultimity classified as data type float64 although it's
mainily intergers to maintain the same data type for easier and faster calculations. 

There are diffrent names for data types in NumPy versus regular Python such as float64 (numpy) vs float (python) but if you even need to check the data type the code is:

In [12]:
#array name, .dtype
array1.dtype

dtype('float64')

Sometimes you need to change one elements data type specficialy, the following code would do that

In [13]:
#first write the data type you want the element to be, than the array name, than where the element is in the array
float(array1[0])

3.0

### NumPy's axis numbering system
In two dimensional and beyond arrays there is an axis that represents the rows and columns of the array. Axis 0 represents the rows and Axis 1 represents the columns in a two dimensional array.


In a one dimensional array the first and only axis is axis 0.

In [14]:
# array2 is two dimensional which means there are two axies 
print(array2.sum(axis=0))
print(array2.sum(axis=1))

#array1 only has one axis because it is one dimensional
print(array1.sum(axis=0))


[125. 325. 219.]
[ 12. 657.]
3669.0


## Vectorization
Def: Vectorization is an operation being performed in Numpy that applies to each element in an array


Vectorization makes it easy and fast to update every element of an array in a simple way.


Example:

In [15]:
#the name of the array, the change you are making to the array
array2+4

array([[  6.,   8.,  10.],
       [127., 325., 217.]])

### Broadcasting
If two arrays have different shapes and they are being used together NumPy try to combine them into a compatible shape for calculation, that is called broadcasting

In [16]:
#array1 is one dimension but array 2 is two dimesions so the output is two dimesions
array1/array2

array([[1.50000000e+00, 8.32500000e+01, 5.55500000e+02],
       [2.43902439e-02, 1.03738318e+00, 1.56478873e+01]])

### ufunc or Universal Functions
Universal function/ufunc work on every element in a NumPy array.


There are several different ufunc's but they all do the same thing of applying a function onto all elements of an array.

In [17]:
#the ufunc here is log base 2 and that function is applied on all the elements of the array
np.log2(array2)

array([[1.        , 2.        , 2.5849625 ],
       [6.94251451, 8.32642949, 7.73470962]])

### How to access and modify values in an ndarray
The formula to access and modify values in an array is: numpy_array[row_selection, column_selection]

For one-dimensional arrays, this simplifies to numpy_array[selection] 

Uses a start index (included) and an end index (excluded) with a colon in between, as in start:end. 

By leaving away the start and end index, you are left with a colon, which therefore stands for all rows or all columns in a two-dimensional array.

In [18]:
print(array2[1,1])

print(array1[2])

print(array2[0,:])

321.0
3333.0
[2. 4. 6.]


### Copy vs View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.


Any changes made to the copy will not affect the original array, and any changes made to the original array will not affect the copy.


The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [19]:
#this is an example of copy as the array doesn't update
array2
#making the copy
subset_2 = array2[:, :2].copy()
print(subset_2)
#editing the copy
subset_2[0, 0] = 50
#printing the copy
print(subset_2)
#printing array with no change
print(array2)

[[  2.   4.]
 [123. 321.]]
[[ 50.   4.]
 [123. 321.]]
[[  2.   4.   6.]
 [123. 321. 213.]]


In [20]:
#this is an example of view as the element updates in the array
print(array2)
#creating the slice of data we are using
subset_1 = array2[:, :2]
print(subset_1)
#chaning the data
subset_1[0, 0] = 50
#printing the array with updated elements 
print(array2)


[[  2.   4.   6.]
 [123. 321. 213.]]
[[  2.   4.]
 [123. 321.]]
[[ 50.   4.   6.]
 [123. 321. 213.]]
